added generic loader script

diff --git a/client/loader b/client/loader
--- a/client/loader
+++ b/client/loader
@@ -1,2 +1,18 @@
 #!/bin/sh
-exec $(cd $(dirname $0)/../lib/tlr && pwd)/$(basename $0) "$@"
+script="$(readlink -f $0)"
+if [ x"$(basename $script)" = x"$(basename $0)" ] ; then
+  cmd="$1"
+  if [ -z "$cmd" ] ; then
+    echo "No command specified" 1>&2
+    exit 1
+  fi
+  shift
+else
+  cmd="$(basename $0)"
+fi
+runscript="$(dirname "$script")/$cmd"
+if [ -L "$runscript" ] ; then
+  echo "Installation Error!" 1>&2
+  exit 2
+fi
+exec "$runscript"  "$@"
