Bug fixes

diff --git a/scripts/groupmgr b/scripts/groupmgr
--- a/scripts/groupmgr
+++ b/scripts/groupmgr
@@ -84,7 +84,7 @@ add)
   if groups_add $newgid "$@" ; then
     apply_policies
   else
-    die $? "Error creating $newgroup"
+    die $? "Error creating $1"
   fi
   ;;
 del)
